language: python
dist: xenial
sudo: true
python:
    - "3.6"

env:
    global:
        PROTOBUF_VERSION=3.6.1

install:   
    - pip install --upgrade pip
    - pip install virtualenv
    - mkdir gmt && cd gmt
    - virtualenv -p python3.6 venv
    - . venv/bin/activate
    - pip install --upgrade setuptools
    - git clone https://github.com/D0WN3D/gobyte-masternode-tool
    - cd gobyte-masternode-tool/
    - pip install -r requirements.txt
    - pyinstaller --distpath=../dist/linux --workpath=../dist/linux/build gobyte_masternode_tool.spec
